version: 2.0.{build}
skip_non_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
artifacts:
- path: AuroraTranslationTool\bin\Release\
  name: Release
deploy:
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  release: Aurora Translation Tool v$(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: 1ugGk17lkq2gESnUH82Dt9Mfa1BQT3KUcqbgQHafLlFM9BOAwQMNUlj5h0jNhCwO
  artifact: Release
  draft: true